version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/foodgram/static/
      - media_volume:/foodgram/media/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/foodgram/static/
      - media_volume:/foodgram/media/
    ports:
      - 80:80
    depends_on:
      - web